### ISSUE TITLE
FastDoll - 1.21.1 support

### ISSUE THREAD

**Issue by notrohit1702** [Basicprogrammer10/minecraft-mods#2]
The latest (1.7) version only supports 1.21 and not 1.21.1. If you change the dependency to 1.21.x, it works perfectly fine on Minecraft 1.21.1. Please update the mod to support the new version.

**Comment by connorslade** [comment]
Thank you for letting me know. I will publish a new release as soon as I can.

**Comment by connorslade** [comment]
Sorry for the delay. I have published a new version of the mod (1.8) with 1.21.1 support on Github and Modrinth.
